### ISSUE TITLE
causes tidypics 'upload photos' process to fail

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/target_blank#5]
i  have been testing elgg 2.1 here with the various plugins that i use in 1.12 and found some bugs when using target_blank alongside tidypics 2.0.0.
when target_blank is enabled, the following occurs:

1. when i click 'upload photos' for an already existing album, i am taken to an error page and see the message 'you cannot access AJAX view directly'.
2. when i click a plugin title in the admin area's plugin list and 'target blank' is activated, i see the same error message and error page.

**Comment by jdalsem** [comment]
Can you confirm that there are no js errors? Is all js finished loading?

**Comment by propertunist** [comment]
looking in the console i see errors relating to the 'live' handler that is now deprecated in JS, so that may well be the only problem:

```$external_links.live is not a function```

**Comment by jdalsem** [comment]
That is old code... did you update to the latest version of target_blank?

**Comment by propertunist** [comment]
ah, i used the latest version from the elgg community - i didn't realise you had a newer version in the github releases section. ;)
i'll test that one, thanks.

**Comment by jdalsem** [comment]
I am assuming this will fix the problem, so closing for now. If you still experience the problem with v4.0 let me know
